const fs=require('fs');let js=fs.readFileSync('app.js','utf8');
const store={};const elems={};
function mkel(){return {value:'',innerText:'',innerHTML:'',style:{},dataset:{},classList:{add(){},remove(){},toggle(){},contains(){return false}},querySelector(){return null},querySelectorAll(){return []},appendChild(){},checked:true,textContent:'',scrollTop:0,scrollHeight:0};}
global.document={getElementById:id=>elems[id]||(elems[id]=mkel()),querySelectorAll:()=>[],addEventListener(){},createElement:mkel};
global.window={addEventListener(){}};
global.localStorage={getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=v,removeItem:k=>delete store[k]};
global.gsap={timeline:()=>{const t={to(){return t},set(){return t}};return t}};
global.Chart=function(){};global.speechSynthesis={getVoices:()=>[],cancel(){},speak(){}};
global.Notification={permission:'default'};global.fetch=()=>Promise.reject('x');
global.SpeechSynthesisUtterance=function(){};global.setInterval=()=>0;global.setTimeout=f=>{};
js+='\nglobal.AI=AI;global.buildTick=buildTick;global.CALC=CALC;';
eval(js);
let pass=0,fail=0;const chk=(n,c)=>{if(c)pass++;else{fail++;console.log('FAIL:',n)}};
const E=id=>document.getElementById(id);
E('p-in').value='800';calcP();chk('paga 713',E('p-neto').innerText.includes('713')&&E('p-atk').innerText.includes('47'));
E('t-bruto').value='600';calcT();chk('trusti 30/60',E('t-p').innerText.includes('30')&&E('t-t').innerText.includes('60'));
E('v-in').value='100';calcV();chk('valuta 108',E('v-USD').innerText.includes('108'));
E('k-d').value='100';E('k-n').value='100';calcK();chk('kesco 13,5',E('k-res').innerText.includes('13,5'));
E('d-vle').value='10000';E('d-kub').value='2000';calcD();chk('dogana 3.800',E('d-res').innerText.includes('3.800'));
E('c-in').value='62000';calcC();chk('crypto 1btc',E('c-btc').innerText.startsWith('1.0'));
E('f-dist').value='100';E('f-cons').value='10';E('f-price').value='1.89';calcF();chk('fuel 18,9',E('f-tot').innerText.includes('18,9')&&E('f-co2').innerText.includes('26.4'));
E('pr-m2').value='100';E('pr-vle').value='500';E('pr-tipi').value='0.0015';E('pr-prim').checked=true;calcPr();chk('prona 52,5',E('pr-tat').innerText.includes('52,5'));
unit='ha';fuelOn=false;E('s-kat').value='216';E('s-val').value='2';calcS();chk('subv 432',E('s-tot').innerText.includes('432'));
chk('AI paga',AI.reply('sa neto per 800 euro').includes('713'));
chk('AI trust',AI.reply('si funksionon trusti').toLowerCase().includes('pension'));
chk('AI fallback no-emoji',/Paga, Trusti/.test(AI.reply('asdf')));
buildTick();chk('tick',E('tick').innerHTML.includes('BTC'));
chk('CALC 9 modules',Object.keys(CALC).length===9);
chk('no greet name',!js.includes('greeting('));
console.log(`\nPASS ${pass} / FAIL ${fail}`);
